server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG
jwt:
  signerKey: "5653d2351dcf482657db6644f88288aebcfbc3a1633c50e6b418e55ba5147bec"
