server:
  port: 8082
  servlet:
    context-path: /products
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/product_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG

