server:
  port: 8888

app:
  api-prefix: /api/v1
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: review_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/review/**
          filters:
            - StripPrefix=2