server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG

