app:
  name-admin: "Quản trị viên"
  email-admin: "21130022@st.hcmuaf.edu.vn"
server:
  port: 8086
  servlet:
    context-path: /orders
spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: "jdbc:mysql://localhost:3306/order_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG

